wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.33
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    t:
      3:
      - 3
      4: 3.8.10
      5: 0.10.33
      8:
      - 1
      - 5
episodes:
  desc: null
  value: 5000
epsilon:
  desc: null
  value: 0.05
gamma:
  desc: null
  value: 0.99
initial_lr:
  desc: null
  value: 1.0
min_lr:
  desc: null
  value: 0.005
n_states:
  desc: null
  value: 40
seed:
  desc: null
  value: 0
