wandb_version: 1

J:
  desc: null
  value: 100
_wandb:
  desc: null
  value:
    cli_version: 0.10.33
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    t:
      1:
      - 5
      2:
      - 5
      3:
      - 3
      4: 3.8.10
      5: 0.10.33
      8:
      - 1
      - 5
algo:
  desc: null
  value: Q_learning
episodes:
  desc: null
  value: 5000
epsilon:
  desc: null
  value: 0.05
gamma:
  desc: null
  value: 0.99
initial_lr:
  desc: null
  value: 0.1
max_steps:
  desc: null
  value: 3000
min_lr:
  desc: null
  value: 0.005
n_states:
  desc: null
  value: 40
seed:
  desc: null
  value: 17
